// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace progettoECommerce.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Carrello", b =>
                {
                    b.Property<int>("CarrelloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProdotto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistrazioneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarrelloId");

                    b.HasIndex("RegistrazioneId");

                    b.ToTable("Carrelli");
                });

            modelBuilder.Entity("Registrazione", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Registrazioni");
                });

            modelBuilder.Entity("Carrello", b =>
                {
                    b.HasOne("Registrazione", "Registrazione")
                        .WithMany("Carrellos")
                        .HasForeignKey("RegistrazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registrazione");
                });

            modelBuilder.Entity("Registrazione", b =>
                {
                    b.Navigation("Carrellos");
                });
#pragma warning restore 612, 618
        }
    }
}
